{"timestamp":"2025-09-05T01:06:22.824404","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-05T01:06:22.825024","level":"info","event":"Filling up the DagBag from /Users/user/airflow/dags/customer_pipeline_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-05T01:06:22.897861Z","level":"error","event":"python(23433) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-05T01:06:22.960598Z","level":"error","event":"python(23434) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-05T01:06:24.345878Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-05T01:06:24.346111Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-05T01:06:24.346970Z","level":"info","event":"Current task name:extract_customers","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-05T01:06:24.347122Z","level":"info","event":"Dag name:customer_pipeline_snowflake","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-05T01:06:24.352862","level":"info","event":"Snowflake Connector for Python Version: 3.17.3, Python Version: 3.12.9, Platform: macOS-10.16-x86_64-i386-64bit","logger":"snowflake.connector.connection"}
{"timestamp":"2025-09-05T01:06:24.353621","level":"info","event":"Connecting to GLOBAL Snowflake domain","logger":"snowflake.connector.connection"}
{"timestamp":"2025-09-05T01:06:30.334140","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"HttpError","exc_value":"290404 (08001): None: 404 Not Found: post WO35181.snowflakecomputing.com:443/session/v1/login-request","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/miniconda3/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/Users/user/airflow/dags/customer_pipeline_dag.py","lineno":90,"name":"extract_customers"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/__init__.py","lineno":54,"name":"Connect"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":588,"name":"__init__"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":972,"name":"connect"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":1371,"name":"__open_connection"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":1704,"name":"authenticate_with_retry"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":1736,"name":"_authenticate"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/auth/_auth.py","lineno":238,"name":"authenticate"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":728,"name":"_post_request"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":847,"name":"fetch"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":988,"name":"_request_exec_wrapper"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":898,"name":"_request_exec_wrapper"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":1193,"name":"_request_exec"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":1142,"name":"_request_exec"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":225,"name":"raise_failed_request_error"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/errors.py","lineno":286,"name":"errorhandler_wrapper"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/errors.py","lineno":344,"name":"hand_to_other_handler"},{"filename":"/opt/miniconda3/lib/python3.12/site-packages/snowflake/connector/errors.py","lineno":217,"name":"default_errorhandler"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-05T01:06:30.346233Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-05T01:06:30.347996Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-05T01:06:30.348197Z","level":"info","event":"Task:<Task(PythonOperator): extract_customers>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-05T01:06:30.348313Z","level":"info","event":"Failure caused by 290404 (08001): None: 404 Not Found: post WO35181.snowflakecomputing.com:443/session/v1/login-request","chan":"stdout","logger":"task"}
